### PR TITLE
Task2mockups

### PR DESCRIPTION
**Pull request by denisbaranchik**
task2 completed

### CODE REVIEW

**Comment by MaksimViarenich** [comment]
Add me as a reviewer, please

**Comment by denisbaranchik** [comment]
> Add me as a reviewer, please

 Could you please accept my invitation to be a collaborator so i add you, i can't do it right now.
image

**Comment by MaksimViarenich** [comment]
> > Add me as a reviewer, please
> 
> Could you please accept my invitation to be a collaborator so i add you, i can't do it right now.
> image

Have you typed my email? mviarenich@exadel.com

**Comment by denisbaranchik** [comment]
> > > Add me as a reviewer, please
> > 
> > 
> > Could you please accept my invitation to be a collaborator so i add you, i can't do it right now.
> > image
> 
> Have you typed my email? [mviarenich@exadel.com](mailto:mviarenich@exadel.com)
 Yes, I tried both your email and github nickname
image

**Comment by MaksimViarenich** [comment]
For user page can't find Log Out

**Comment by MaksimViarenich** [comment]
Everything else is fine. Good job!

**Comment by MaksimViarenich** [comment]
Can't find the logic for remove
Снимок экрана 2020-02-24 в 20 43 37

**Pull request merged**
